### ISSUE TITLE
refactor ActionSMBase starting logic

### ISSUE THREAD

**Issue by minhnh** [b-it-bots/mas_execution_manager#17]
Currently, the following logic to start state machine execution is repetitive in all action servers:

```python
self.action_sm.goal = goal
self.action_sm.result = None
self.action_sm.execution_requested = True
while not self.action_sm.result:
    if self.action_server.is_preempt_requested():
        self.action_sm.preempted = True
        rospy.sleep(0.05)
    self.action_server.set_succeeded(self.action_sm.result)
```

It may make sense to move it to the definition of `ActionSMBase` in an `execute()` function and include preemption and timeout logic there.

**Comment by argenos** [comment]
@minhnh is this for find my mates?

**Comment by alex-mitrevski** [comment]
@argenos This is independent of a scenario; it's just a refactoring issue to remove some code repetition in the action servers.

**Comment by argenos** [comment]
If you’ve got a date in mind, can you add this to a project? Otherwise leave it as is for now

**Comment by alex-mitrevski** [comment]
Resolved by https://github.com/b-it-bots/mas_execution_manager/pull/18
