### ISSUE TITLE
add verification for state machine YAML

### ISSUE THREAD

**Issue by minhnh** [b-it-bots/mas_execution_manager#5]
* list of states should match the states defined in the YAML file
* state transitions should only be to listed states
* state outcomes match transition `name`

This can potentially be used for unit tests as well.

**Comment by alex-mitrevski** [comment]
The functionality for verifying the state machine config as well as unit tests for the config parser were added in PR https://github.com/b-it-bots/mas_execution_manager/pull/14

The verification that the state outcomes match the transition names is related to issue https://github.com/b-it-bots/mas_execution_manager/issues/11; if we generate the state skeletons automatically, we will not have troubles with this. But we can't really verify that the states actually return the expected outcomes without proper unit tests.
