### ISSUE TITLE
create a separated abstraction layer for actions

### ISSUE THREAD

**Issue by minhnh** [b-it-bots/mas_execution_manager#6]
Scenario states may be too simple to justify creating an action server, or maybe already associated with services, but can still benefit from some basic parsing like `sm_id`, `state_name` currently provided in `ScenarioStateBase`. Since this concerns structural changes, I'd also suggest:
* Enforce `@abstractmethod` flags and throw errors if derived classes don't extend these methods
* Add comment documentation under these methods to describe what their intended purposes are
* An `initialize` abstract method may be helpful for centralizing code specific to the derived class. This also removes the necessity for redefining `__init__` with the `super` call all the time
* Throws an error if waiting for the action server times out

**Comment by alex-mitrevski** [comment]
What would be the benefit of using action servers here? Can you provide an example of what you mean? The execution manager is a state machine library, not an action library...

Why would we not define a constructor and instead use an `initialize` method that practically achieves the same purpose?

**Comment by minhnh** [comment]
`ScenarioStateBase` is currently meant for action servers/skills right? considering that the method `get_dispatch_msg` is for creating a message "action client associated with the state." What I meant is not all state needs creating an action server, but there can be a lower level of abstraction here which handles filling out general state machine information for simpler states.

A separated `initialize` would allow better timing control for state initialization. A simple example would be if you want to `loginfo(self.action_name)` in the base class right after initialization is complete. Personally, I have used this for waiting until loading of detection model is complete before broadcasting the detection action server.

**Comment by alex-mitrevski** [comment]
I've just realised I never answered this. `ScenarioStateBase` is not for actions, it's for scenario states and, more generally, behaviours.

For actions, we have the [`ActionSMBase`](https://github.com/b-it-bots/mas_execution_manager/blob/master/common/mas_execution/action_sm_base.py) class, which is based on a [fault-tolerant state machine](https://github.com/b-it-bots/ftsm) and does have dedicated methods for initialisation, recovery, etc.
