### ISSUE TITLE
State machine visualiser

### ISSUE THREAD

**Issue by alex-mitrevski** [b-it-bots/mas_execution_manager#9]
For simplifying the debugging process, it would be very useful to have a visualiser for a state machine defined with the definition language, such that the visualisation would include the states and the named transitions between them.

A few months ago, I had a prototype of this using [networkx](https://networkx.github.io), but I can't seem to find my script anymore (it seems I never pushed it).

**Comment by minhnh** [comment]
You mean visualizer for this state machine used in ROPOD, and not `smach_viewer` for `smach` states I'm assuming. Maybe it's helpful for linking to the relevant state machine definitions and repositories?

**Comment by alex-mitrevski** [comment]
This issue is now about FTSM; it's about reading a state machine definition file and generating a state machine diagram from it (what people have been doing manually for the scenarios in the last few days).

**Comment by sthoduka** [comment]
output from SDP project:
![tmp](https://user-images.githubusercontent.com/5426162/59093309-e6bc6100-8913-11e9-93ae-65ca7499b000.png)

**Comment by alex-mitrevski** [comment]
This is mostly fine; the only improvement I can think of would be displaying the initial state and the terminal states with different colours so that it's easier to go through the diagram.

**Comment by alex-mitrevski** [comment]
Closed by https://github.com/b-it-bots/mas_execution_manager/pull/21
